### ISSUE TITLE
Sharphound 2.4.1 declared some users as a group, e.g. the MSOL_ accounts (in Neo4J)

### ISSUE THREAD

**Issue by HerrHozi** [BloodHoundAD/SharpHound#103]
Hi,

I figured out, that some users will be declared as a group, these objects also have three labels.

labels(s)[0] = 'Group'
labels(s)[1] = 'User'
labels(s)[2] = 'Base'

instead of

labels(s)[0] = 'User'
labels(s)[1] = 'Base'

try this in your lab e.g. with the following query:

`match (s) where labels(s)[0] = 'Group' return s.name,s.lastlogontimestamp,  labels(s)[0],labels(s)[1],labels(s)[2] order by s.lastlogontimestamp`

![2024-06-04_104911](https://github.com/BloodHoundAD/SharpHound/assets/96825160/148f2600-60a7-47f1-9f1f-2bae042c4892)

but BH5  CE shows the object, as a correct type.

![2024-06-04_105253](https://github.com/BloodHoundAD/SharpHound/assets/96825160/d9dadf62-df8e-40f2-be4e-7122189e66ca)

This is a bug in Sharphound 2.4.1?

TIA
- Holger

**Comment by rvazarkar** [comment]
I believe we've fixed this in https://github.com/SpecterOps/BloodHound/pull/741
