### ISSUE TITLE
performance regression in 2.5.x 

### ISSUE THREAD

**Issue by kokanin** [BloodHoundAD/SharpHound#112]
2.4.1 pulls 150 objects/second, 2.5.x pulls around 1.5, causing my patience to expire before collection finishes

**Comment by StephenHinck** [comment]
@kokanin - we pulled SharpHound v2.5.4 from BloodHound v5.13.0 for these concerns. We're working on a fix and expect to have a new v2.5.X version available here shortly!

**Comment by rvazarkar** [comment]
https://github.com/BloodHoundAD/SharpHound/releases/tag/v2.5.6

We published v2.5.6, give it a try and see if it works for you

**Comment by kokanin** [comment]
2.5.6 hovers around 2.5-2.7 objects/second

**Comment by rvazarkar** [comment]
What collection methods are you using? We've tested this in several different environments now and have not seen performance like that anywhere

**Comment by kokanin** [comment]
At least the ACL collection slows things to a crawl:
Group -> starts around 40 obj/s, ends up at 250 obj/s 
Localgroup -> 30 obj/s
LocalAdmin -> 30 obj/s
Session -> 30 obj/s
ACL -> 3 obj/s

**Comment by rvazarkar** [comment]
Would it be possible to run with `-v 0` and get us the logs or is this sensitive data?

**Comment by rvazarkar** [comment]
I believe we identified the source of this slowdown and fixed it in https://github.com/BloodHoundAD/SharpHound/releases/tag/v2.5.7

**Comment by kokanin** [comment]
ACL collection going at 500 obj/s using 2.5.7 so it seems you fixed that part, thanks! It is still floating around 30 obj/s when doing -c All but I can live with this.
