### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by APT256** [BloodHoundAD/SharpHound#115]
I am interested in using Bloodhound as a defensive tool. That being said, are there any plans for Sharphound to continuously send data back to Bloodhound via encrypted channels?

**Comment by StephenHinck** [comment]
Hi @servebeer, thanks for your request! That's one of the features of BloodHound Enterprise, which is explicitly focused on the defensive use case. You can learn more about BloodHound Enterprise on the [SpecterOps website](https://specterops.io/bloodhound-overview/). The differences between CE and Enterprise are specifically shown [here](https://specterops.io/bloodhound-feature-comparison/)!

Feel free to contact our team for a demo on the website if you want more information!

**Comment by APT256** [comment]
Thanks Stephen!

v/r
Jon
