### ISSUE TITLE
Unable to collect the data using sharphound

### ISSUE THREAD

**Issue by vijayeee** [BloodHoundAD/SharpHound#14]
I am trying to run the following: Sharphound.exe -d abc.xyz --domaincontroller 10.x.x.x -c DCOnly --ldapusername user@abc.xyz --ldappassword mypassword

But the server where I ran the executable is in ghi.jkl.mno.mydomain  

I get the error as below,

Creating schema map for domain abc.xyz using path CN=Schema, CN=Configuration, DC=jkl, DC=mno, DC=mydomain

I understand that it is still picks up only the DC of the server from where sharphound is running and not checking for the remote DC. I don't have a trust relationship between abc.xyz and ghi.jkl.mno.mydomain.

**Comment by rvazarkar** [comment]
You can try v1.0.3. Reopen this issue if the problem persists
