### ISSUE TITLE
Unable to connect to LDAP, verify your credentials

### ISSUE THREAD

**Issue by PocketDC** [BloodHoundAD/SharpHound#19]
Saw this as a closed issue, having trouble with it today using both the compiled SharpHound and the one packaged with Bloodhound

![sharp](https://user-images.githubusercontent.com/29924527/165325178-be941461-16a3-44fa-9b03-67f05a0222c5.png)

**Comment by PocketDC** [comment]
FWIW running it through execute-assembly worked, so could be something on the host side

**Comment by rvazarkar** [comment]
If it works through execute-assembly, I'm just going to guess your session token was invalid. Closing this issue for now
