### ISSUE TITLE
Issue with the latest SharpHound version  (1.0.3) + BloodHound 4.1.0

### ISSUE THREAD

**Issue by LyesH4ck** [BloodHoundAD/SharpHound#23]
Hello, 

I think there is a problem with the latest version of SharpHound 1.0.3. Some queries are impossible in BH and there is a big difference between SharHound 1.03 / BloodHound 4.1 and SharpHound.ps1 / Bloodhound 4.0.3 (cf. screenshots).
 
FYI, all tests are performed with the same user on the same machine and I used the same query : Shortest Path To Here on DC04.

SharpHound 1.0.3 + BloodHound 4.1.0

[20220530053518_BloodHound.zip](https://github.com/BloodHoundAD/SharpHound/files/8797345/20220530053518_BloodHound.zip)

![image](https://user-images.githubusercontent.com/10633285/170579367-95f480fe-8cbc-4aad-ac83-4409d2de086b.png)

SharpHound.ps1 + BloodHound 4..0.3

[20220530060550_BloodHound.zip](https://github.com/BloodHoundAD/SharpHound/files/8797457/20220530060550_BloodHound.zip)

![image](https://user-images.githubusercontent.com/10633285/170579576-dd04e137-ee72-4272-bd99-5e3712aca83c.png)

Bloodhound.py + Bloodhound 4.1.0

[20220530114827_bloodhound.zip](https://github.com/BloodHoundAD/SharpHound/files/8797349/20220530114827_bloodhound.zip)

![image](https://user-images.githubusercontent.com/10633285/170579665-1c3c58d7-d5ae-4721-a8e1-11414c051407.png)

Thank you.

**Comment by LyesH4ck** [comment]
Hello,

FYI I've updated my post by uploading the dump for each technique I used. Maybe that will help you if you want to compare the results ?

**Comment by rvazarkar** [comment]
If this is related to local group edges, its likely that your lab computers are getting caught by the password age check. I'll be adding a flag to skip that check

**Comment by yellow-starburst** [comment]
+1 had the same problem.

**Comment by rvazarkar** [comment]
We added the `--SkipPasswordCheck` flag to bypass this check. You can use that going forward
