### ISSUE TITLE
Collection of data from DC with specified flags

### ISSUE THREAD

**Issue by vijayeee** [BloodHoundAD/SharpHound#25]
I have an issue with data collection from an active directory that actually has 200k accounts. The collection of data is running for long time (more than 3 days), though I used the the flag -c DCOnly. Is there any additonal flag that I can use to collect the data faster?

**Comment by rvazarkar** [comment]
Can you run collection using individual collection methods to try and determine if theres one particular method thats causing this?

**Comment by vijayeee** [comment]
Can you provide the collection method parameters here ? I will try with that

**Comment by JonasBK** [comment]
Here: https://bloodhound.readthedocs.io/en/latest/data-collection/sharphound-all-flags.html

**Comment by StephenHinck** [comment]
Closing as no additional information has been provided. Please feel free to re-open if you have any additional information to help us troubleshoot.
