### ISSUE TITLE
Error in Consumer - CollectionMethod All

### ISSUE THREAD

**Issue by TealAlex** [BloodHoundAD/SharpHound#34]
Hi,

I get the same error as in https://github.com/BloodHoundAD/SharpHound/issues/15 when using the collection method "all" or GPOLocalGroups. 
This seems to me that the collection method all does execute the GPOLocalGroups collection which it should not if I understand the picture here correctly https://bloodhound.readthedocs.io/en/latest/data-collection/sharphound-all-flags.html

Regards
Alex

[GPOLocalGroup.txt](https://github.com/BloodHoundAD/SharpHound/files/9982212/GPOLocalGroup.txt)
[All.txt](https://github.com/BloodHoundAD/SharpHound/files/9982213/All.txt)

**Comment by StephenHinck** [comment]
Hey Alex, I don't believe this is still an active issue. Let us know if you're still experiencing it.
