### ISSUE TITLE
SharpHound.ps1 fails to run in Azure Cloud Shell

### ISSUE THREAD

**Issue by terryf82** [BloodHoundAD/SharpHound#39]
After uploading the pre-built [SharpHound.ps1](https://github.com/BloodHoundAD/BloodHound/blob/master/Collectors/SharpHound.ps1) script to an Azure Cloud Shell session, attempting to run it generates the following error:

```
PS /home/terry> . .\SharpHound.ps1
PS /home/terry> Invoke-BloodHound -CollectionMethod all                                                                                              MethodInvocationException: /home/terry/SharpHound.ps1:638
Line |
 638 |      $Assembly = [Reflection.Assembly]::Load($UncompressedFileBytes)
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Load" with "1" argument(s): "Bad IL format."
InvalidOperation: /home/terry/SharpHound.ps1:641
Line |
 641 |      $Assembly.GetType("Costura.AssemblyLoader", $false).GetMethod("At …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation: /home/terry/SharpHound.ps1:642
Line |
 642 |      $Assembly.GetType("Sharphound.Program").GetMethod("InvokeSharpHou …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```

The reason for using SharpHound powershell rather than the AzureHound binary is that the later requires authentication to execute (even in Cloud Shell), but I'm unsure if that's the case for SharpHound?

**Comment by JonasBK** [comment]
Hi @terryf82,

Are you trying to collect data from Azure or on-prem AD? Because SharpHound cannot collect data from Azure, only AzureHound can do that.

But it is correct that AzureHound requires authentication the collect data from Azure.

**Comment by terryf82** [comment]
Sounds like I was using the wrong tool then, thanks for clarifying.
