### ISSUE TITLE
Bloodhound-python KRB_AP_ERR_BAD_INTEGRITY(Integrity check on decrypted field failed)

### ISSUE THREAD

**Issue by Rickyso** [BloodHoundAD/SharpHound#54]
Hello!
I'm using bloodhound-python to dump from various DCs, two of them work fine but the third one gives me this error:
Tried to match the server's time, no luck.
I couldn't find anything useful online.
Any idea why this is happening? Thanks!

**Comment by JonasBK** [comment]
Hi @Rickyso,

I have removed your screenshot from the comment to avoid having credentials publicly exposed.
The python version of SharpHound is not maintained by the BloodHound team but by Dirk-jan Mollema and is hosted here: https://github.com/fox-it/BloodHound.py 
That said, you are DCSyncing with a user of another domain (maybe forest) - are you sure you have rights for that in the targeted domain?

**Comment by rvazarkar** [comment]
Closing, please move this to the correct repo
