### ISSUE TITLE
CollectAllProperties Does not Appear To Collect All Properties

### ISSUE THREAD

**Issue by McBartok** [BloodHoundAD/SharpHound#56]
Adding the "--collectallproperties" tag to get additional all LDAP information does not appear to collect anything additional.

The below image shows a comparison of a collection run with (left) and without (right) the "--collectallproperties" tag.

![image](https://github.com/BloodHoundAD/SharpHound/assets/7973777/662c519e-abb3-4601-8894-85aab8c29c55)

Full commands that was run:
`SharpHound.exe --collectionmethods All,GPOLocalGroup --domain TestDom.corp --prettyprint`
`SharpHound.exe --collectionmethods All,GPOLocalGroup --domain TestDom.corp --prettyprint --collectallproperties`

**Comment by rvazarkar** [comment]
Finally managed to track down whats going on with this bug. Will work on a fix

**Comment by rvazarkar** [comment]
Fixed in v2.0.1
