### ISSUE TITLE
SkipRegistryLoggedOn option not used

### ISSUE THREAD

**Issue by leechristensen** [BloodHoundAD/SharpHound#58]
SharpHound is documented as having a command line option called [skipregistryloggedon](https://github.com/BloodHoundAD/SharpHound/blob/f4d613b596c5dc55dc963fcd6b8acaf86c15d89e/README.md?plain=1#L102). 

However, looking in the code, this option does not actually do anything.  The value is obtained [here](
https://github.com/BloodHoundAD/SharpHound/blob/f4d613b596c5dc55dc963fcd6b8acaf86c15d89e/src/Sharphound.cs#L359), but doesn't seem to be referenced anywhere else in the SharpHound/SharpHoundCommon repositories.

Given that the default behavior has been to use registry session collection, might consider remove this command line option.

**Comment by rvazarkar** [comment]
Fixed in 2.0.0
