### ISSUE TITLE
Stuck at upload 0%

### ISSUE THREAD

**Issue by SoulXHades** [BloodHoundAD/SharpHound#63]
Hi! Recently I used SharpHound v2.0.0 to collect data. However, when I attempted to upload the ZIP file into BloodHound, it stays at 0% forever. Only `_computers.json` faces this issue. The rest of the JSON files are fine. If I use back the older version of SharpHound such as v1.1.0, it works fine. 

![image](https://github.com/BloodHoundAD/SharpHound/assets/18703340/7cc80ea5-461d-4b34-9141-d16854e1facd)

**Comment by ChrisTruncer** [comment]
I have also encountered this same issue. Not sure of a way forward at the moment.

**Comment by mikal70** [comment]
I have the same issue.Only stuck with computers.json, others can be upload.

**Comment by rvazarkar** [comment]
You appear to be using legacy bloodhound to upload the data, and using a 2.0 collector to collect. The 2 versions aren't compatible. If you want to use legacy bloodhound you'll need to use one of the 1.X collectors, otherwise switch to BloodHound CE

**Comment by SoulXHades** [comment]
I just realized I installed  Bloodhound via apt-get which their latest version is only v4.3.1.

**Comment by StephenHinck** [comment]
As @rvazarkar mentioned, SharpHound v2+ is only compatible with BloodHound CE, you'll need to match those versions for successful ingest.

**Comment by ez-lbz** [comment]
Thanks for the reply!!!
