### ISSUE TITLE
Microsoft Defender Reporting Successful Login Attempts

### ISSUE THREAD

**Issue by ikspozd** [BloodHoundAD/SharpHound#69]
Hello,

Does SharpHound.ps1 attempt to log into workstations when querying AD?

Thanks

**Comment by StephenHinck** [comment]
Workstation logons will be attempted only if you are enumerating local group memberships and/or sessions. These will be non-interactive logons.

**Comment by ikspozd** [comment]
@StephenHinck is there a way to disable that feature?

**Comment by StephenHinck** [comment]
If you choose not to use those collection methods, it will not be attempted. You'd want to avoid methods such as All, ComputerOnly, Session, LoggedOn, etc

See: https://support.bloodhoundenterprise.io/hc/en-us/articles/17481375424795-All-SharpHound-Community-Edition-Flags-Explained

**Comment by ikspozd** [comment]
Excellent thanks!
