### ISSUE TITLE
Sharphound --CollectionMethods all is not working properly

### ISSUE THREAD

**Issue by PiyushThePal** [BloodHoundAD/SharpHound#83]
After running sharphound command in various ways using ps1 and exe extension on windows to gather information. The gather is mostly not proper. Looking at the below 2 screenshots it can be observed that even after trying several times to run sharp hound in various ways. I failed to receive expected data.

![image](https://github.com/BloodHoundAD/SharpHound/assets/46394419/1090de92-8189-4d9e-882d-4a9a6e109d62)
Figure 1# Expected Output

![image](https://github.com/BloodHoundAD/SharpHound/assets/46394419/4c89058c-51e6-46a7-a371-c55ba9ad4d72)
Figure 2# Getting this Output even after various tries. (Only got once the expected output by luck.)

If we take a look closely the complete jeffadmin path is missing and this can be really a big flaw.
I'm am using all the latest versions and even tried with 4.3.0 but still no luck.

Please fix this ASAP.

**Comment by JonasBK** [comment]
Hi @PiyushThePal,

I assume the missing edge from the Computer Client74 to Jeffadmin is a HasSession edge. Collecting that requires:
- The account running the SharpHound collection is a member of Administrators on Client74 (unless it is an old Windows version)
- The Client74 computer is running and the computer where SharpHound is running from can reach Client74 on port 455
- Jeffadmin has a session on Client74

Also, be aware that you need the right collector version:
SharpHound v1.x -> Works with BloodHound 4.x
SharpHound v2.x -> Works with BloodHound 5.x

Let me know if that doesn't help you.
